(defun temp ()
  (interactive)
  (back-to-indentation)
  (forward-sexp)
  (forward-sexp)
  (back-to-indentation)
  (forward-char)
  (forward-sexp)
  (print (integerp (elisp--preceding-sexp)))
  (when (integerp (elisp--preceding-sexp))
	(back-to-indentation)
	(forward-char)
	(insert "file ")))
