(include "../library.dl")

(defun + (&rest values)
  (var sum 0)
  (while (not (null? values))
            (to sum (+ (first values)))
            (pop values))
  sum)

(defun part (part)
  (println "------------------------------------------------------------------------------------------------------------")
  (println "Part " part)
  (println "------------------------------------------------------------------------------------------------------------"))

(defun result (result)
  (println "Result: " result))

(var input (if release
               (include "input")
               (include "example")))
(println "Input: " input)
